FROM python:3.11-alpine3.18

LABEL maintainer="Xu@nCh3n"

ENV TZ=Asia/Shanghai LANG=zh_CN.UTF-8

RUN set -eux && \
        \
        apk --no-cache update && apk -U --no-cache add git && \
        \
        mkdir -p /usr/src/myapp/ && \
        git clone https://github.com/Ccccx159/Media-Download-Helper.git /usr/src/myapp/ && \
        python3 -m pip install --no-cache-dir python-qbittorrent requests -q; 

ENTRYPOINT ["python3"]
CMD ["/usr/src/myapp/main.py"]