version: '3'
services:
  media_dlhelper:
    build:
      context: .
      dockerfile: dockerfile
    image: b1gfac3c4t/media_dlhelper:v2.0.0
    environment:
      - TZ=Asia/Shanghai
      # 这里所有的环境变量都不要使用引号
      # 必填参数
      - QBIT_HOST=<your qbittorrent WebUI base API>
      - QBIT_USER=<your qbittorrent username>
      - QBIT_PASS=<your qbittorrent password>
      - BOT_TOKEN=<your telegram bot token>
      - TMDB_API_TOKEN=<your TMDB API token>
      - GOOGLE_APPS_SCRIPT_URL=<google apps scrip 部署后的原始web应用网址>
      # 可选参数
      - LOG_LEVEL=INFO # [DEBUG, INFO, WARNING] 三个等级，默认 WARNING
      - LOG_EXPORT=False # [True, False0] 是否将日志输出到文件，默认 False
      - LOG_PATH=/var/tmp/media_dlhelper_logs/ # 默认 /var/tmp/media_dlhelper_logs/
    network_mode: "bridge"
